### ISSUE TITLE
ava.security.AccessControlException when using new "Flat" Look and Feel

### ISSUE THREAD

**Issue by EdoFro** [EdoFro/Freeplane_MarkdownHelper#9]
MarkdownHelper dialog produces errors with the the new "Flat" Look&Feel options in Freeplane.

I still don't know why.
I don't know if the error is from the MDH addon or Freeplane or the Flat LaF implementation.

Here is the Log message that appears:

```
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.security.AccessControlException: access denied ("java.awt.AWTPermission" "watchMousePointer")
STDERR: at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
STDERR: at java.base/java.security.AccessController.checkPermission(AccessController.java:1036)
STDERR: at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
STDERR: at org.freeplane.plugin.script.InternationalizedSecurityManager.checkPermission(InternationalizedSecurityManager.java:215)
STDERR: at java.desktop/java.awt.MouseInfo.getPointerInfo(MouseInfo.java:81)
STDERR: at com.formdev.flatlaf.ui.FlatPopupFactory.fixToolTipLocation(FlatPopupFactory.java:225)
STDERR: at com.formdev.flatlaf.ui.FlatPopupFactory.getPopup(FlatPopupFactory.java:71)
STDERR: at java.desktop/javax.swing.ToolTipManager.showTipWindow(ToolTipManager.java:350)
STDERR: at java.desktop/javax.swing.ToolTipManager.mouseMoved(ToolTipManager.java:623)
STDERR: at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:338)
STDERR: at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6681)
STDERR: at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3360)
STDERR: at java.desktop/java.awt.Component.processEvent(Component.java:6405)
STDERR: at java.desktop/java.awt.Container.processEvent(Container.java:2263)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
STDERR: at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
STDERR: at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4561)
STDERR: at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by EdoFro** [comment]
I think it's solved in [release v0.1.6](https://github.com/EdoFro/Freeplane_MarkdownHelper/releases/tag/v0.1.6)
